custom_rules:
  invalid_todo_makring:
    name: "Invalid TODO format"
    regex: "\\/\\/\\s(to do)(\\s|:)"
    match_kinds: comment
    message: "Use 'TODO:' format"
    severity: warning
  todo_youtrack:
    name: "TODO without YouTrack reference"
    regex: "\\/\\/\\s(TODO|TO DO|FIX|FIXME|FIX ME):(?!.*\\[FRONT\\-\\d+\\])[^\\n]"
    message: "Do not add TODOs without a task link reference. Create new task and add Issue Id to comment. Use 'TODO: [FRONT-task_number]' format"
    severity: warning
warning_threshold: 1
disabled_rules:
  - trailing_whitespace
  - type_name
  - todo
  - void_function_in_ternary
  - large_tuple
  - blanket_disable_command
opt_in_rules:
  - empty_count
  - private_outlet
type_body_length:
  warning: 210
function_body_length:
  warning: 80
file_length:
  warning: 450
  error: 500
identifier_name:
  severity: warning
  min_length: 3
  excluded:
    - id
    - vc
excluded:
  - ../../**/Pods
  - ../../**/Generated
  - ../../**/build
  - ../../**/Example

