-dontwarn dev.nonoxy.common.coroutines.DispatchersKt
-dontwarn dev.nonoxy.core.design.theme.ThemeKt
-dontwarn dev.nonoxy.core.navigation.Screen$Rooms
-dontwarn dev.nonoxy.feature.rooms.di.FeatureRoomsImplModuleKt
-dontwarn dev.nonoxy.feature.rooms.presentation.navigation.FeatureRoomsNavigationKt