name: iOS Checks

on:
  pull_request:
    branches: [ develop ]

jobs:
  ios-lint:
    name: SwiftLint + SwiftFormat
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install SwiftLint & SwiftFormat
        run: brew install swiftlint swiftformat

      - name: SwiftLint
        run: cd linters/swiftlint && swiftlint lint --strict ../../iosApp/

      - name: SwiftFormat
        if: always()
        run: cd linters/swiftformat && swiftformat --lint ../../iosApp/

  unit-tests:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5.6.0
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v6

      - name: Run unit tests
        run: ./gradlew iosSimulatorArm64Test

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: '**/build/test-results/iosSimulatorArm64Test/*.xml'
          retention-days: 1
